##
## EPITECH PROJECT, 2021
## zappy
## File description:
## Makefile
##

all:	client string cstring list

client:
	make -C client/ -s

string:
	make -C string/ -s

cstring:
	make -C cstring/ -s

list:
	make -C list/ -s

clean:
	make clean -C client/ -s
	make clean -C string/ -s
	make clean -C cstring/ -s
	make clean -C list/ -s

fclean:
	make fclean -C client/ -s
	make fclean -C string/ -s
	make fclean -C cstring/ -s
	make fclean -C list/ -s

re:
	make re -C client/ -s
	make re -C string/ -s
	make re -C cstring/ -s
	make re -C list/ -s

.PHONY: all client string cstring list clean fclean re