//
// Created by Patrick Eiermann on 08/06/2021.
//

#ifndef B_YEP_410_STG_4_1_ZAPPY_PATRICK_EIERMANN_MAP_HPP
#define B_YEP_410_STG_4_1_ZAPPY_PATRICK_EIERMANN_MAP_HPP


class Map {

};


#endif //B_YEP_410_STG_4_1_ZAPPY_PATRICK_EIERMANN_MAP_HPP
